// src/lib/demo-data.ts
// Used when NEXT_PUBLIC_DEMO_MODE=true (Vercel public deployment)
// Simulates a realistic 24-hour incident history

import { Incident, AuditEntry, DashboardStats } from './types'

export const DEMO_INCIDENTS: Incident[] = [
  {
    incident_id: 'inc-f3a9b2c1',
    created_at: new Date(Date.now() - 1000 * 60 * 4).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 1).toISOString(),
    status: 'in_triage',
    title: 'CrashLoopBackOff — payments-api after v2.4.0 deploy',
    severity: 'critical',
    namespace: 'payments',
    service: 'payments-api',
    deployment: 'payments-api',
    pod: 'payments-api-7d9f84-xk2pq',
    image_tag: 'payments-api:v2.4.0',
    incident_type: 'crash_loop',
    probable_root_cause: 'v2.4.0 introduced a missing STRIPE_API_VERSION environment variable. Application panics on startup at config validation. CrashLoopBackOff triggered 90 seconds after rollout completion. Evidence: restart count 7 in 4 minutes, log line "FATAL: required env var STRIPE_API_VERSION not set" appears in all 7 crash cycles.',
    confidence_score: 0.94,
    supporting_evidence: [
      "Log: 'FATAL: required env var STRIPE_API_VERSION not set' — appears in all 7 restarts",
      'Rollout: payments-api image changed to v2.4.0 at 14:32 UTC — 90s before first crash',
      'Alert: KubePodCrashLooping fired at 14:33:28 UTC (restarts=7 in 4min)',
      'Previous version v2.3.9 ran without incident for 18 days',
    ],
    recommended_action: 'rollout_restart',
    requires_approval: true,
    grouped_alert_count: 7,
    alerts: [
      { alertname: 'KubePodCrashLooping', severity: 'critical', namespace: 'payments', service: 'payments-api', pod: 'payments-api-7d9f84-xk2pq', deployment: 'payments-api' },
      { alertname: 'KubeDeploymentReplicasMismatch', severity: 'high', namespace: 'payments', service: 'payments-api', deployment: 'payments-api' },
    ],
    logs: [
      { timestamp: new Date(Date.now() - 60000 * 3).toISOString(), level: 'fatal', message: 'FATAL: required env var STRIPE_API_VERSION not set — aborting startup' },
      { timestamp: new Date(Date.now() - 60000 * 3.5).toISOString(), level: 'error', message: 'config.Validate() failed: 1 validation error: stripe_api_version is required' },
      { timestamp: new Date(Date.now() - 60000 * 4).toISOString(), level: 'info', message: 'Starting payments-api v2.4.0 — loading config from environment' },
    ],
    rollout_events: [
      { deployment: 'payments-api', namespace: 'payments', image: 'payments-api:v2.4.0', revision: 12, started_at: new Date(Date.now() - 60000 * 6).toISOString(), status: 'complete' },
      { deployment: 'payments-api', namespace: 'payments', image: 'payments-api:v2.3.9', revision: 11, started_at: new Date(Date.now() - 60000 * 60 * 24 * 18).toISOString(), status: 'complete' },
    ],
  },
  {
    incident_id: 'inc-a7e2d4f8',
    created_at: new Date(Date.now() - 1000 * 60 * 23).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
    status: 'resolved',
    title: 'High p95 latency — order-service (2.8s threshold breach)',
    severity: 'high',
    namespace: 'orders',
    service: 'order-service',
    deployment: 'order-service',
    pod: null,
    image_tag: 'order-service:v3.1.2',
    incident_type: 'high_latency',
    probable_root_cause: 'Traffic spike 3.2x baseline at market open caused order-service CPU to hit throttling limit (500m). All 3 replicas running at 98% CPU. p95 latency rose from 140ms to 2800ms. Scale-out to 7 replicas resolved within 90 seconds.',
    confidence_score: 0.89,
    supporting_evidence: [
      'HTTP RPS increased from 420 to 1340 at 09:00:03 UTC (market open)',
      'CPU throttling: all 3 replicas at limit (500m/500m) for 4 minutes',
      'p95 latency: 140ms → 2800ms over 6-minute window',
      'No recent deployments — traffic-driven incident',
    ],
    recommended_action: 'scale_up',
    requires_approval: false,
    grouped_alert_count: 3,
    last_action: {
      type: 'scale_up',
      result: 'Scaled order-service from 3 to 7 replicas. Recovery confirmed in 94 seconds.',
      success: true,
      ts: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    },
    alerts: [
      { alertname: 'HighResponseTime', severity: 'high', namespace: 'orders', service: 'order-service' },
      { alertname: 'HighErrorRate', severity: 'warning', namespace: 'orders', service: 'order-service' },
    ],
    logs: [
      { timestamp: new Date(Date.now() - 60000 * 20).toISOString(), level: 'warn', message: 'Request processing time 2340ms (threshold: 500ms) path=/api/v1/orders' },
      { timestamp: new Date(Date.now() - 60000 * 21).toISOString(), level: 'error', message: 'context deadline exceeded after 3000ms — downstream timeout' },
      { timestamp: new Date(Date.now() - 60000 * 22).toISOString(), level: 'warn', message: 'CPU throttling detected — worker pool at capacity (32/32 threads)' },
    ],
    rollout_events: [
      { deployment: 'order-service', namespace: 'orders', image: 'order-service:v3.1.2', revision: 8, started_at: new Date(Date.now() - 60000 * 60 * 72).toISOString(), status: 'complete' },
    ],
  },
  {
    incident_id: 'inc-c5b8e3a2',
    created_at: new Date(Date.now() - 1000 * 60 * 55).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
    status: 'resolved',
    title: 'OOMKilled — 2/3 user-service pods killed under load',
    severity: 'high',
    namespace: 'users',
    service: 'user-service',
    deployment: 'user-service',
    pod: 'user-service-5c7d9b-m3np1',
    image_tag: 'user-service:v1.8.4',
    incident_type: 'oom_kill',
    probable_root_cause: 'User-service memory limit (512Mi) too low for current session cache size. 2/3 pods hit OOMKill simultaneously during evening peak. Memory growth traced to unbounded session cache introduced in v1.8.4. Scaled from 3→6 replicas as temporary mitigation. Permanent fix requires cache eviction policy.',
    confidence_score: 0.91,
    supporting_evidence: [
      'Pod status: OOMKilled reason for pods user-service-5c7d9b-m3np1 and user-service-5c7d9b-xp9k2',
      'container_memory_working_set_bytes reached 511Mi (limit: 512Mi) before kill',
      'Memory growth pattern: linear increase over 4 hours (leak signature)',
      'v1.8.4 changelog mentions new in-memory session store — no eviction policy set',
    ],
    recommended_action: 'scale_up',
    requires_approval: false,
    grouped_alert_count: 2,
    last_action: {
      type: 'scale_up',
      result: 'Scaled user-service from 3 to 6 replicas. Memory per pod dropped to ~180Mi. Recovery confirmed.',
      success: true,
      ts: new Date(Date.now() - 1000 * 60 * 44).toISOString(),
    },
    alerts: [
      { alertname: 'KubeContainerOOMKilled', severity: 'high', namespace: 'users', service: 'user-service', pod: 'user-service-5c7d9b-m3np1' },
    ],
    logs: [
      { timestamp: new Date(Date.now() - 60000 * 53).toISOString(), level: 'error', message: 'signal: killed — OOMKiller terminated process (rss=534Mi, limit=512Mi)' },
      { timestamp: new Date(Date.now() - 60000 * 54).toISOString(), level: 'warn', message: 'session_cache size=182304 entries — no eviction policy configured' },
      { timestamp: new Date(Date.now() - 60000 * 56).toISOString(), level: 'warn', message: 'memory usage at 94% of limit (481Mi/512Mi) — GC pressure increasing' },
    ],
    rollout_events: [
      { deployment: 'user-service', namespace: 'users', image: 'user-service:v1.8.4', revision: 5, started_at: new Date(Date.now() - 60000 * 60 * 4).toISOString(), status: 'complete' },
    ],
  },
  {
    incident_id: 'inc-9d1f7a3e',
    created_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 95).toISOString(),
    status: 'resolved',
    title: 'KubePodCrashLooping — inventory-worker config error',
    severity: 'warning',
    namespace: 'inventory',
    service: 'inventory-worker',
    deployment: 'inventory-worker',
    pod: 'inventory-worker-8b4c2d-zq7rx',
    image_tag: 'inventory-worker:v2.1.0',
    incident_type: 'crash_loop',
    probable_root_cause: 'ConfigMap update removed KAFKA_BROKER_LIST key. inventory-worker fails on broker connection at startup. Rollout restart after ConfigMap fix resolved the issue.',
    confidence_score: 0.87,
    supporting_evidence: [
      "Log: 'Error connecting to Kafka: broker list is empty'",
      'ConfigMap aiops/inventory-config updated 3 minutes before incident — KAFKA_BROKER_LIST key removed',
      'Previous pod revision worked correctly for 6 days',
    ],
    recommended_action: 'rollout_restart',
    requires_approval: false,
    grouped_alert_count: 4,
    last_action: {
      type: 'rollout_restart',
      result: 'Rollout restart triggered. Recovery confirmed in 45 seconds.',
      success: true,
      ts: new Date(Date.now() - 1000 * 60 * 98).toISOString(),
    },
    alerts: [
      { alertname: 'KubePodCrashLooping', severity: 'warning', namespace: 'inventory', service: 'inventory-worker' },
    ],
    logs: [
      { timestamp: new Date(Date.now() - 60000 * 118).toISOString(), level: 'error', message: 'Error connecting to Kafka: broker list is empty — check KAFKA_BROKER_LIST env var' },
    ],
    rollout_events: [],
  },
  {
    incident_id: 'inc-2e8c4b7d',
    created_at: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 155).toISOString(),
    status: 'escalated',
    title: 'KubeNodeMemoryPressure — worker-node-3 approaching eviction',
    severity: 'high',
    namespace: 'kube-system',
    service: null,
    deployment: null,
    pod: null,
    image_tag: null,
    incident_type: 'node_pressure',
    probable_root_cause: 'Worker node ip-10-0-2-87 running at 91% memory utilisation. 14 pods scheduled, 3 are high-memory ML inference workloads. Kubelet eviction threshold (85%) breached. Node-level intervention required — cannot be auto-remediated.',
    confidence_score: 0.78,
    supporting_evidence: [
      'Node condition: MemoryPressure=True on ip-10-0-2-87',
      'node_memory_MemAvailable_bytes: 820Mi remaining (total: 16Gi)',
      '3 ML inference pods using 2.1Gi each — total 6.3Gi from 3 pods',
      'Kubelet eviction policy: memory.available < 1Gi',
    ],
    recommended_action: 'notify_only',
    requires_approval: true,
    grouped_alert_count: 1,
    alerts: [
      { alertname: 'KubeNodeMemoryPressure', severity: 'high', namespace: 'kube-system', pod: 'ip-10-0-2-87' },
    ],
    logs: [],
    rollout_events: [],
  },
]

export const DEMO_STATS: DashboardStats = {
  total_open: 2,
  critical_count: 1,
  resolved_today: 3,
  avg_resolution_minutes: 14,
  noise_reduction_pct: 43,
  auto_resolved_pct: 67,
  mttr_improvement_pct: 58,
}

export const DEMO_AUDIT: AuditEntry[] = [
  { ts: new Date(Date.now() - 60000 * 1).toISOString(), event_type: 'reasoning_complete', incident_id: 'inc-f3a9b2c1', incident_type: 'crash_loop', confidence_score: 0.94, recommended_action: 'rollout_restart', requires_approval: true },
  { ts: new Date(Date.now() - 60000 * 8).toISOString(), event_type: 'action_executed', incident_id: 'inc-a7e2d4f8', action_type: 'scale_up', target: 'orders/order-service', actor: 'executor', success: true, result: 'Scaled to 7 replicas' },
  { ts: new Date(Date.now() - 60000 * 10).toISOString(), event_type: 'reasoning_complete', incident_id: 'inc-a7e2d4f8', incident_type: 'high_latency', confidence_score: 0.89, recommended_action: 'scale_up', requires_approval: false },
  { ts: new Date(Date.now() - 60000 * 44).toISOString(), event_type: 'action_executed', incident_id: 'inc-c5b8e3a2', action_type: 'scale_up', target: 'users/user-service', actor: 'executor', success: true, result: 'Scaled to 6 replicas' },
  { ts: new Date(Date.now() - 60000 * 98).toISOString(), event_type: 'action_executed', incident_id: 'inc-9d1f7a3e', action_type: 'rollout_restart', target: 'inventory/inventory-worker', actor: 'executor', success: true, result: 'Rollout restart triggered' },
  { ts: new Date(Date.now() - 60000 * 100).toISOString(), event_type: 'approval_decision', incident_id: 'inc-9d1f7a3e', approved: true, approver: 'srajan@platform', action_type: 'rollout_restart' },
]

export const TIMELINE_DATA = [
  { time: '00:00', incidents: 0, resolved: 0 },
  { time: '03:00', incidents: 1, resolved: 0 },
  { time: '06:00', incidents: 1, resolved: 1 },
  { time: '09:00', incidents: 3, resolved: 1 },
  { time: '12:00', incidents: 2, resolved: 3 },
  { time: '15:00', incidents: 1, resolved: 2 },
  { time: '18:00', incidents: 2, resolved: 1 },
  { time: '21:00', incidents: 1, resolved: 2 },
  { time: 'now',   incidents: 2, resolved: 0 },
]
